baseURL = "https://theorize.co/"
title = "Pondering new theories every day!"
author = "Jeremiah Brazeau"
languageCode = "en-us"
theme = "monopriv"
canonifyurls = true
paginate = 3
enableEmoji = true
summaryLength = 20
googleAnalytics = "G-M5XCESZV5Z"

[params]
about = "A place for thinking out loud"
linkedin = "https://www.linkedin.com/in/jeremiah-brazeau-17282b3/"
email = "theorize.co@gmail.com"
analytics = true
commento = true

[params.hero]
enabled = true
img = "img/selfie.png"

